/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMatchesRouteImport } from './routes/dashboard.matches'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as DashboardBookRouteImport } from './routes/dashboard.book'
import { Route as AdminTournamentsRouteImport } from './routes/admin.tournaments'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMatchesRoute = DashboardMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookRoute = DashboardBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/dashboard/book': typeof DashboardBookRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/matches': typeof DashboardMatchesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/dashboard/book': typeof DashboardBookRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/matches': typeof DashboardMatchesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/dashboard/book': typeof DashboardBookRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/matches': typeof DashboardMatchesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/complete-profile'
    | '/dashboard'
    | '/login'
    | '/admin/announcements'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/customers'
    | '/admin/gallery'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/revenue'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/tournaments'
    | '/dashboard/book'
    | '/dashboard/bookings'
    | '/dashboard/matches'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/support'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete-profile'
    | '/login'
    | '/admin/announcements'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/customers'
    | '/admin/gallery'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/revenue'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/tournaments'
    | '/dashboard/book'
    | '/dashboard/bookings'
    | '/dashboard/matches'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/support'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/complete-profile'
    | '/dashboard'
    | '/login'
    | '/admin/announcements'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/customers'
    | '/admin/gallery'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/revenue'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/tournaments'
    | '/dashboard/book'
    | '/dashboard/bookings'
    | '/dashboard/matches'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/support'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/matches': {
      id: '/dashboard/matches'
      path: '/matches'
      fullPath: '/dashboard/matches'
      preLoaderRoute: typeof DashboardMatchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/book': {
      id: '/dashboard/book'
      path: '/book'
      fullPath: '/dashboard/book'
      preLoaderRoute: typeof DashboardBookRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTournamentsRoute: typeof AdminTournamentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTournamentsRoute: AdminTournamentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardBookRoute: typeof DashboardBookRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardMatchesRoute: typeof DashboardMatchesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBookRoute: DashboardBookRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardMatchesRoute: DashboardMatchesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
